[package]
name = "dice_roller"
version = "0.1.0"
authors = ["Blockchain realms"]
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
anchor-lang = "0.27.0"
chainlink-solana = "0.2.0"

[features]
no-entrypoint = []